login: &login
  adapter: mysql2
  host: localhost
  username: root
  password: rootpassword

development: &development
  database: rg_local
  <<: *login

test: &test
  database: rg_test
  <<: *login

production: &production
  adapter: mysql2
  host: localhost
  database: your_production_database
  username: your_production_database_login
  password: your_production_database_password
